<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Llm\Abstractions\Upload\06d309e4ead54d3da16a1e4ec649b80a\**" />
    <Compile Remove="Llm\Abstractions\Upload\1a8d4bfaf29044b6898cbe96fbe8996c\**" />
    <Compile Remove="Llm\Abstractions\Upload\320ea86db3414c99af4881453c8fe0b2\**" />
    <Compile Remove="Llm\Abstractions\Upload\392a0038fc9f466e93e393f3a4841954\**" />
    <Compile Remove="Llm\Abstractions\Upload\3c3b13f0cf484d96aa0be3a4562fa3b4\**" />
    <Compile Remove="Llm\Abstractions\Upload\4a74cdc5c9b34816af7eb8b3f689f0b6\**" />
    <Compile Remove="Llm\Abstractions\Upload\543a28638c474294bf26371b3d6f5e9a\**" />
    <Compile Remove="Llm\Abstractions\Upload\5d339ed23dc8493c9da1897bd664b5a5\**" />
    <Compile Remove="Llm\Abstractions\Upload\95083afd13da4f7bbca1ed5743f474d0\**" />
    <Compile Remove="Llm\Abstractions\Upload\9e5e4e764aa24f7b9354d52e9bc21bf7\**" />
    <Compile Remove="Llm\Abstractions\Upload\b8866b5924c749c89a467fe925596b39\**" />
    <Compile Remove="Llm\Abstractions\Upload\b8d49192f9814df0b3a336da7678b795\**" />
    <Compile Remove="Llm\Abstractions\Upload\f5dc8a79c3564130b1d848c45d73192e\**" />
    <Compile Remove="Llm\Connectors\OpenAI\**" />
    <Compile Remove="Llm\Connectors\OpenAI\**" />
    <Content Remove="Llm\Abstractions\Upload\06d309e4ead54d3da16a1e4ec649b80a\**" />
    <Content Remove="Llm\Abstractions\Upload\1a8d4bfaf29044b6898cbe96fbe8996c\**" />
    <Content Remove="Llm\Abstractions\Upload\320ea86db3414c99af4881453c8fe0b2\**" />
    <Content Remove="Llm\Abstractions\Upload\392a0038fc9f466e93e393f3a4841954\**" />
    <Content Remove="Llm\Abstractions\Upload\3c3b13f0cf484d96aa0be3a4562fa3b4\**" />
    <Content Remove="Llm\Abstractions\Upload\4a74cdc5c9b34816af7eb8b3f689f0b6\**" />
    <Content Remove="Llm\Abstractions\Upload\543a28638c474294bf26371b3d6f5e9a\**" />
    <Content Remove="Llm\Abstractions\Upload\5d339ed23dc8493c9da1897bd664b5a5\**" />
    <Content Remove="Llm\Abstractions\Upload\95083afd13da4f7bbca1ed5743f474d0\**" />
    <Content Remove="Llm\Abstractions\Upload\9e5e4e764aa24f7b9354d52e9bc21bf7\**" />
    <Content Remove="Llm\Abstractions\Upload\b8866b5924c749c89a467fe925596b39\**" />
    <Content Remove="Llm\Abstractions\Upload\b8d49192f9814df0b3a336da7678b795\**" />
    <Content Remove="Llm\Abstractions\Upload\f5dc8a79c3564130b1d848c45d73192e\**" />
    <Content Remove="Llm\Connectors\OpenAI\**" />
    <Content Remove="Llm\Connectors\OpenAI\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\06d309e4ead54d3da16a1e4ec649b80a\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\1a8d4bfaf29044b6898cbe96fbe8996c\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\320ea86db3414c99af4881453c8fe0b2\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\392a0038fc9f466e93e393f3a4841954\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\3c3b13f0cf484d96aa0be3a4562fa3b4\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\4a74cdc5c9b34816af7eb8b3f689f0b6\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\543a28638c474294bf26371b3d6f5e9a\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\5d339ed23dc8493c9da1897bd664b5a5\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\95083afd13da4f7bbca1ed5743f474d0\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\9e5e4e764aa24f7b9354d52e9bc21bf7\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\b8866b5924c749c89a467fe925596b39\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\b8d49192f9814df0b3a336da7678b795\**" />
    <EmbeddedResource Remove="Llm\Abstractions\Upload\f5dc8a79c3564130b1d848c45d73192e\**" />
    <EmbeddedResource Remove="Llm\Connectors\OpenAI\**" />
    <EmbeddedResource Remove="Llm\Connectors\OpenAI\**" />
    <None Remove="Llm\Abstractions\Upload\06d309e4ead54d3da16a1e4ec649b80a\**" />
    <None Remove="Llm\Abstractions\Upload\1a8d4bfaf29044b6898cbe96fbe8996c\**" />
    <None Remove="Llm\Abstractions\Upload\320ea86db3414c99af4881453c8fe0b2\**" />
    <None Remove="Llm\Abstractions\Upload\392a0038fc9f466e93e393f3a4841954\**" />
    <None Remove="Llm\Abstractions\Upload\3c3b13f0cf484d96aa0be3a4562fa3b4\**" />
    <None Remove="Llm\Abstractions\Upload\4a74cdc5c9b34816af7eb8b3f689f0b6\**" />
    <None Remove="Llm\Abstractions\Upload\543a28638c474294bf26371b3d6f5e9a\**" />
    <None Remove="Llm\Abstractions\Upload\5d339ed23dc8493c9da1897bd664b5a5\**" />
    <None Remove="Llm\Abstractions\Upload\95083afd13da4f7bbca1ed5743f474d0\**" />
    <None Remove="Llm\Abstractions\Upload\9e5e4e764aa24f7b9354d52e9bc21bf7\**" />
    <None Remove="Llm\Abstractions\Upload\b8866b5924c749c89a467fe925596b39\**" />
    <None Remove="Llm\Abstractions\Upload\b8d49192f9814df0b3a336da7678b795\**" />
    <None Remove="Llm\Abstractions\Upload\f5dc8a79c3564130b1d848c45d73192e\**" />
    <None Remove="Llm\Connectors\OpenAI\**" />
    <None Remove="Llm\Connectors\OpenAI\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Scripts\BGE_reranker.py" />
    <None Remove="Assets\Scripts\BM25_reranker.py" />
    <None Remove="Assets\Scripts\flash_reranker.py" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Assets\Scripts\BGE_reranker.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AdditionalFiles>
    <AdditionalFiles Include="Assets\Scripts\BM25_reranker.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AdditionalFiles>
    <AdditionalFiles Include="Assets\Scripts\flash_reranker.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AdditionalFiles>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Castle.Core" Version="5.1.1" />
	  <PackageReference Include="CSnakes.Runtime" Version="1.2.0" />
    <PackageReference Include="jieba.NET" Version="0.42.2" />
    <PackageReference Include="LLamaSharp" Version="0.23.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.23.0" />
    <PackageReference Include="LLamaSharp.kernel-memory" Version="0.23.0" />
    <PackageReference Include="LLamaSharp.semantic-kernel" Version="0.23.0" />
    <PackageReference Include="MailKit" Version="4.7.1.1" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Masuit.Tools.Core" Version="2.6.9.4" />
    <PackageReference Include="Microsoft.AspNet.Cors" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.KernelMemory.AI.OpenAI" Version="0.98.250324.1" />
    <PackageReference Include="Microsoft.KernelMemory.Core" Version="0.98.250324.1" />
    <PackageReference Include="Microsoft.KernelMemory.MemoryDb.Postgres" Version="0.98.250324.1" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.68.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Planners.Handlebars" Version="1.15.0-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Core" Version="1.15.0-alpha" />
    <PackageReference Include="Microsoft.SemanticKernel.Plugins.Memory" Version="1.15.0-alpha" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="Minio" Version="6.0.2" />
    <PackageReference Include="ModelContextProtocol" Version="0.1.0-preview.10" />
    <PackageReference Include="MongoDB.Driver" Version="2.28.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.2.0" />
    <PackageReference Include="PuppeteerSharp" Version="20.0.5" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.145" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.4.1" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
	  <PackageReference Include="System.Linq.Async" Version="6.0.1">
		  <ExcludeAssets>compile</ExcludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\DTOs\" />
    <Folder Include="Assets\Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Resources\char_state_tab.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Resources\pos_prob_emit.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Resources\pos_prob_start.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Resources\pos_prob_trans.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Resources\prob_emit.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Resources\prob_trans.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Scripts\requirements.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Scripts\stopwords.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\AgentPrompt.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\DataAnalysis.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\Default.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\FunctionManual.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\RAGPrompt.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\RewritePrompt.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\StaticPages.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\Stepwise.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\SubTask.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\TaskPlanner.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\Text2SQL.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\UseMcpTool.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\UseMcp.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Common\Prompts\VueComponent.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\cn_synonym.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\dict.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\idf.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\stopwords.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Common\Prompts\*.txt" />
  </ItemGroup>

</Project>
