version: '3.8'

services:
  wikit_minio:
    image: quay.io/minio/minio
    container_name: wikit_minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9010:9000"
      - "9011:9001"
    command: server /data --console-address ":9001"

volumes:
  minio_data: