import java.io.*;
import java.util.*;

public class Main {
    public static void main(String[] args) throws IOException {
        // Generate sample data
        List<String[]> records = new ArrayList<>();
        records.add(new String[]{"id", "name", "city", "score"});

        for (int i = 1; i <= 25; i++) {
            records.add(new String[]{
                String.valueOf(i),
                "Person_" + i,
                "City_" + (i % 10 + 1),
                String.valueOf(100 - i)
            });
        }

        // Write to CSV
        String csvPath = "java_export.csv";
        try (PrintWriter writer = new PrintWriter(new FileWriter(csvPath))) {
            for (String[] record : records) {
                writer.println(String.join(",", record));
            }
        }
        System.out.println("CSV exported: " + csvPath);

        // Write to text file
        String txtPath = "summary_report.txt";
        try (PrintWriter writer = new PrintWriter(new FileWriter(txtPath))) {
            writer.println("=".repeat(50));
            writer.println("Data Export Summary Report");
            writer.println("=".repeat(50));
            writer.println();
            writer.println("Total Records: " + (records.size() - 1));
            writer.println("Generated by: Java Data Export");
            writer.println();
            writer.println("Sample Data:");
            for (int i = 1; i <= Math.min(5, records.size() - 1); i++) {
                writer.println("  " + String.join(" | ", records.get(i)));
            }
            writer.println();
            writer.println("=".repeat(50));
            writer.println("End of Report");
        }
        System.out.println("Report saved: " + txtPath);

        System.out.println("Export complete!");
    }
}
