// <auto-generated />
using Gridify.Learning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gridify.Learning.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240923075634_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Gridify.Learning.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike1",
                            Color = "Blue",
                            ModelName = "Soria Tank1",
                            Sku = "X000006482043"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nike2",
                            Color = "Black",
                            ModelName = "Soria Tank2",
                            Sku = "X000006482044"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Nike3",
                            Color = "White",
                            ModelName = "Soria Tank3",
                            Sku = "X000006482045"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Nike4",
                            Color = "Red",
                            ModelName = "Soria Tank5",
                            Sku = "X000006482046"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
